import type { FlowCompoundDefinition } from '../types';

/** Commerce triggers (Shopify Flow–style order lifecycle) */
export const COMMERCE_TRIGGERS: FlowCompoundDefinition[] = [
  {
    id: 'commerce.order.created',
    kind: 'trigger',
    label: 'Order created',
    description: 'Runs when a new order is placed in the storefront.',
    category: 'commerce',
    emoji: '🛒',
    legacyTriggerType: 'ORDER_CREATED',
    configFields: [
      {
        key: 'orderSource',
        label: 'Order source',
        type: 'select',
        options: [
          { value: 'any', label: 'Any channel' },
          { value: 'storefront', label: 'Storefront only' },
          { value: 'admin', label: 'Admin draft' },
        ],
        defaultValue: 'any',
      },
    ],
  },
  {
    id: 'commerce.order.drafted',
    kind: 'trigger',
    label: 'Order drafted',
    description: 'Runs when an order is saved as a draft before checkout completes.',
    category: 'commerce',
    emoji: '📝',
    legacyTriggerType: 'ORDER_DRAFTED',
    configFields: [],
  },
  {
    id: 'commerce.payment.sent',
    kind: 'trigger',
    label: 'Payment sent',
    description: 'Runs when payment is captured or marked as sent for an order.',
    category: 'commerce',
    emoji: '💳',
    legacyTriggerType: 'PAYMENT_SENT',
    configFields: [
      {
        key: 'paymentStatus',
        label: 'Payment status',
        type: 'select',
        options: [
          { value: 'paid', label: 'Paid' },
          { value: 'authorized', label: 'Authorized' },
          { value: 'partially_paid', label: 'Partially paid' },
        ],
        defaultValue: 'paid',
      },
    ],
  },
  {
    id: 'commerce.order.updated',
    kind: 'trigger',
    label: 'Order updated',
    description: 'Runs when order fields or line items change.',
    category: 'commerce',
    emoji: '✏️',
    legacyTriggerType: 'ORDER_UPDATED',
    configFields: [],
  },
];

export const LEARNER_TRIGGERS: FlowCompoundDefinition[] = [
  {
    id: 'learner.course.completed',
    kind: 'trigger',
    label: 'Course completed',
    description: 'When a learner finishes a published course.',
    category: 'learner',
    emoji: '🎓',
    legacyTriggerType: 'COURSE_COMPLETED',
    configFields: [],
  },
  {
    id: 'learner.user.enrolled',
    kind: 'trigger',
    label: 'User enrolled',
    description: 'When a user enrolls in a course or program.',
    category: 'learner',
    emoji: '✅',
    legacyTriggerType: 'USER_ENROLLED',
    configFields: [],
  },
  {
    id: 'learner.group.joined',
    kind: 'trigger',
    label: 'Group joined',
    description: 'When a user joins a learner group.',
    category: 'learner',
    emoji: '👥',
    legacyTriggerType: 'GROUP_JOINED',
    configFields: [],
  },
  {
    id: 'learner.certificate.issued',
    kind: 'trigger',
    label: 'Certificate issued',
    description: 'When a completion certificate is generated.',
    category: 'learner',
    emoji: '🏆',
    legacyTriggerType: 'CERTIFICATE_ISSUED',
    configFields: [],
  },
];

export const CORE_TRIGGERS: FlowCompoundDefinition[] = [
  {
    id: 'core.schedule.cron',
    kind: 'trigger',
    label: 'Scheduled event',
    description: 'Runs on a recurring schedule (cron).',
    category: 'core',
    emoji: '🕐',
    legacyTriggerType: 'SCHEDULE',
    configFields: [
      { key: 'cron', label: 'Cron expression', type: 'cron', required: true, placeholder: '0 9 * * 1' },
      { key: 'timezone', label: 'Timezone', type: 'string', defaultValue: 'UTC' },
    ],
  },
  {
    id: 'core.webhook.received',
    kind: 'trigger',
    label: 'Webhook received',
    description: 'Triggered by an external HTTP POST to your tenant webhook URL.',
    category: 'core',
    emoji: '🔗',
    legacyTriggerType: 'WEBHOOK',
    configFields: [
      { key: 'secretHeader', label: 'Secret header name', type: 'string', placeholder: 'X-LuxGen-Signature' },
    ],
  },
];

export const DEVELOPER_TRIGGERS: FlowCompoundDefinition[] = [
  {
    id: 'developer.code.staged',
    kind: 'trigger',
    label: 'Code change staged',
    description: 'When Agent Studio stages files for review.',
    category: 'developer',
    emoji: '📝',
    legacyTriggerType: 'CODE_CHANGE_STAGED',
    configFields: [],
  },
  {
    id: 'developer.code.committed',
    kind: 'trigger',
    label: 'Code change committed',
    description: 'When an agent commit lands on a branch.',
    category: 'developer',
    emoji: '✔️',
    legacyTriggerType: 'CODE_CHANGE_COMMITTED',
    configFields: [],
  },
  {
    id: 'developer.code.merged',
    kind: 'trigger',
    label: 'Code change merged',
    description: 'When an agent branch merges to main.',
    category: 'developer',
    emoji: '🔀',
    legacyTriggerType: 'CODE_CHANGE_MERGED',
    configFields: [],
  },
  {
    id: 'developer.code.failed',
    kind: 'trigger',
    label: 'Code change failed',
    description: 'When validation or an agent run fails.',
    category: 'developer',
    emoji: '⚠️',
    legacyTriggerType: 'CODE_CHANGE_FAILED',
    configFields: [],
  },
];

export const CONDITION_COMPOUNDS: FlowCompoundDefinition[] = [
  {
    id: 'core.condition.field_equals',
    kind: 'condition',
    label: 'Field equals',
    description: 'Compare a payload field to a value.',
    category: 'core',
    emoji: '◆',
    configFields: [
      { key: 'field', label: 'Field path', type: 'string', required: true, placeholder: 'order.total' },
      {
        key: 'operator',
        label: 'Operator',
        type: 'select',
        options: [
          { value: 'equals', label: 'Equals' },
          { value: 'not_equals', label: 'Does not equal' },
        ],
        defaultValue: 'equals',
      },
      { key: 'value', label: 'Value', type: 'string', required: true },
    ],
  },
  {
    id: 'core.condition.field_contains',
    kind: 'condition',
    label: 'Field contains',
    description: 'Check if a string field contains text.',
    category: 'core',
    emoji: '◆',
    configFields: [
      { key: 'field', label: 'Field path', type: 'string', required: true },
      { key: 'value', label: 'Contains', type: 'string', required: true },
    ],
  },
  {
    id: 'commerce.condition.order_tag',
    kind: 'condition',
    label: 'Order has tag',
    description: 'True when the order includes a specific tag.',
    category: 'commerce',
    emoji: '🏷️',
    configFields: [{ key: 'tag', label: 'Tag', type: 'string', required: true }],
  },
  {
    id: 'commerce.condition.order_total',
    kind: 'condition',
    label: 'Order total',
    description: 'Compare order total against an amount.',
    category: 'commerce',
    emoji: '💰',
    configFields: [
      {
        key: 'operator',
        label: 'Operator',
        type: 'select',
        options: [
          { value: 'gte', label: 'Greater than or equal' },
          { value: 'lte', label: 'Less than or equal' },
        ],
        defaultValue: 'gte',
      },
      { key: 'amountCents', label: 'Amount (cents)', type: 'number', required: true },
    ],
  },
];

export const ACTION_COMPOUNDS: FlowCompoundDefinition[] = [
  {
    id: 'commerce.order.update_fields',
    kind: 'action',
    label: 'Update order fields',
    description: 'Set tags, notes, or custom fields on the order.',
    category: 'commerce',
    emoji: '{/}',
    legacyActionType: 'UPDATE_ORDER_FIELDS',
    configFields: [
      { key: 'note', label: 'Internal note', type: 'string' },
      { key: 'tags', label: 'Tags (comma-separated)', type: 'string' },
      { key: 'customFields', label: 'Custom fields (JSON)', type: 'json', placeholder: '{"priority":"high"}' },
    ],
  },
  {
    id: 'commerce.order.add_tags',
    kind: 'action',
    label: 'Add order tags',
    description: 'Append tags without replacing existing ones.',
    category: 'commerce',
    emoji: '🏷️',
    legacyActionType: 'TAG_USER',
    configFields: [{ key: 'tags', label: 'Tags', type: 'string', required: true }],
  },
  {
    id: 'core.notification.send_email',
    kind: 'action',
    label: 'Send email',
    description: 'Send a transactional email to the customer or staff.',
    category: 'core',
    emoji: '✉️',
    legacyActionType: 'SEND_EMAIL',
    configFields: [
      {
        key: 'template',
        label: 'Template',
        type: 'select',
        options: [
          { value: 'order_confirmation', label: 'Order confirmation' },
          { value: 'custom', label: 'Custom body' },
        ],
        defaultValue: 'order_confirmation',
      },
      { key: 'subject', label: 'Subject', type: 'string' },
    ],
  },
  {
    id: 'core.notification.notify_slack',
    kind: 'action',
    label: 'Notify Slack',
    description: 'Post a message to a Slack channel.',
    category: 'core',
    emoji: '💬',
    legacyActionType: 'NOTIFY_SLACK',
    configFields: [{ key: 'channel', label: 'Channel', type: 'string', required: true, placeholder: '#orders' }],
  },
  {
    id: 'core.schedule.delay_event',
    kind: 'action',
    label: 'Schedule delayed action',
    description: 'Queue a follow-up action after a delay.',
    category: 'core',
    emoji: '⏱️',
    legacyActionType: 'CALL_WEBHOOK',
    configFields: [
      { key: 'delayMinutes', label: 'Delay (minutes)', type: 'number', required: true, defaultValue: 60 },
      {
        key: 'followUpAction',
        label: 'Follow-up compound ID',
        type: 'string',
        placeholder: 'core.notification.send_email',
      },
    ],
  },
  {
    id: 'learner.enrollment.add_to_group',
    kind: 'action',
    label: 'Add to group',
    description: 'Add the learner to a group.',
    category: 'learner',
    emoji: '👥',
    legacyActionType: 'ADD_TO_GROUP',
    configFields: [{ key: 'groupId', label: 'Group ID', type: 'string' }],
  },
  {
    id: 'learner.course.enroll',
    kind: 'action',
    label: 'Enroll in course',
    description: 'Enroll the user in another course.',
    category: 'learner',
    emoji: '📚',
    legacyActionType: 'ENROLL_IN_COURSE',
    configFields: [{ key: 'courseId', label: 'Course ID', type: 'string' }],
  },
  {
    id: 'developer.agent.run_task',
    kind: 'action',
    label: 'Run agent task',
    description: 'Execute an AI Studio headless task.',
    category: 'developer',
    emoji: '🤖',
    legacyActionType: 'RUN_AGENT_TASK',
    configFields: [{ key: 'prompt', label: 'Prompt', type: 'string', required: true }],
  },
];

export const WAIT_COMPOUNDS: FlowCompoundDefinition[] = [
  {
    id: 'core.wait.delay',
    kind: 'wait',
    label: 'Wait',
    description: 'Pause the flow for a number of seconds before the next step.',
    category: 'core',
    emoji: '🕐',
    configFields: [{ key: 'seconds', label: 'Seconds', type: 'duration', required: true, defaultValue: 10 }],
  },
];

export const FLOW_COMPOUND_CATALOG: FlowCompoundDefinition[] = [
  ...COMMERCE_TRIGGERS,
  ...LEARNER_TRIGGERS,
  ...CORE_TRIGGERS,
  ...DEVELOPER_TRIGGERS,
  ...CONDITION_COMPOUNDS,
  ...ACTION_COMPOUNDS,
  ...WAIT_COMPOUNDS,
];
