FROM node:20-alpine

RUN apk add --no-cache curl

WORKDIR /app

RUN npm install -g turbo@latest

COPY package.json package-lock.json turbo.json ./
COPY scripts/docker ./scripts/docker
COPY apps/web/package.json ./apps/web/
COPY packages ./packages

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["sh", "scripts/docker/web-dev-entrypoint.sh"]
