version: '3.8'

services:
  # Development API Server with hot reload
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    environment:
      NODE_ENV: development
      DEBUG: luxgen:*
      LOG_LEVEL: debug
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/node_modules
    command: npm run dev:api
    ports:
      - "4000:4000"
      - "9229:9229"  # Debug port

  # Development Web Application with hot reload
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_DEBUG: true
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/.next
    command: npm run dev:web
    ports:
      - "3000:3000"
      - "3001:3001"  # Next.js dev server

  # Development Tools with live reload
  dev-tools:
    command: >
      sh -c "
        npm install &&
        npm run dev:all
      "
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: true

  # MongoDB with development data
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: luxgen_dev
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_dev_data:/data/db

  # Redis with development configuration
  redis:
    command: redis-server --appendonly yes --loglevel debug
    volumes:
      - redis_dev_data:/data

volumes:
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local
