/** Re-export @luxgen/automation-flow for tower UI and API consumers in apps/web */
export {
  TOWER_FLOW_VERSION,
  FLOW_COMPOUND_CATALOG,
  getFlowCompound,
  listFlowCompounds,
  exportAutomationSchema,
  createOrderCreatedFlow,
  createEmptyFlow,
  flowToOrderedSteps,
  flowToGraphSteps,
  flowToLegacyAutomation,
  flowNodeToStepView,
  validateTowerFlowDocument,
  parseTowerFlowDocument,
  collectTowerFlowGraphWarnings,
  connectFlowEdge,
  disconnectFlowEdge,
  getNode,
  getOutgoingEdge,
  listIncomingEdges,
  listOutgoingEdges,
  insertFlowNodeAfter,
  insertFlowStepAfter,
  removeFlowNode,
  removeFlowStep,
  moveFlowNode,
  moveFlowStep,
  spliceNodeAfter,
  normalizeEdgeLabel,
} from '@luxgen/automation-flow';

export type {
  TowerFlowDocument,
  FlowNode,
  FlowEdge,
  FlowStepView,
  FlowGraphStepView,
  FlowGraphBranchView,
  FlowGraphWarning,
  FlowCompoundDefinition,
  FlowConfigField,
  FlowNodeKind,
  FlowEdgeLabel,
  AutomationSchemaExport,
} from '@luxgen/automation-flow';
