/** Re-export @luxgen/storefront profile layer for apps/web consumers. */
export {
  DEFAULT_STOREFRONT_CONTENT,
  DEFAULT_STOREFRONT_THEME,
  DEFAULT_STOREFRONT_SLUG,
  DEFAULT_STOREFRONT_ROUTES,
  STOREFRONT_LANDING_PATH,
  LUXGEN_STOREFRONT_TENANT_SUBDOMAINS,
  resolveStorefrontProfile,
  resolveNavHref,
  storefrontThemeCssVars,
  interpolateStorefrontText,
  resolveStorefrontSettings,
  defaultStorefrontSettings,
  isTrainerLandingEnabled,
  toStorefrontPayload,
  landingPathFromSlug,
  matchesStorefrontSlug,
  slugFromLandingPath,
  normalizeStorefrontSlug,
  buildLearnifyCatalog,
  filterPublishedCourses,
} from '@luxgen/storefront';

export type {
  StorefrontNavLink,
  StorefrontCategory,
  StorefrontTestimonial,
  StorefrontHeroContent,
  StorefrontSectionContent,
  StorefrontStatsLabels,
  StorefrontCtaContent,
  StorefrontFooterContent,
  StorefrontContentSettings,
  StorefrontThemeSettings,
  StorefrontBrandingSnapshot,
  StorefrontProfile,
  StorefrontRouteSettings,
  TenantStorefrontSettings,
  StorefrontSettingsPayload,
  ResolveStorefrontProfileInput,
  LearnifyCatalog,
  LearnifyCatalogCourse,
  LearnifyCategory,
  LearnifyInstructor,
} from '@luxgen/storefront';
